// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZv2KyNB1tUS65ltj7eyOGQ_0w6QaOVKc',
    appId: '1:902634485806:web:0c0f479514e66e8c6e47bf',
    messagingSenderId: '902634485806',
    projectId: 'hostelmesss-9d0f2',
    authDomain: 'hostelmesss-9d0f2.firebaseapp.com',
    storageBucket: 'hostelmesss-9d0f2.firebasestorage.app',
    measurementId: 'G-D4T6J9BEX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByDa_uOmaWKpMjscVWwNyqzjGu32Ve2pU',
    appId: '1:902634485806:android:adae2cd2e4a99bf16e47bf',
    messagingSenderId: '902634485806',
    projectId: 'hostelmesss-9d0f2',
    storageBucket: 'hostelmesss-9d0f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ6KVjsC1Vlu_1HBA53qco0BR3wGsDDwo',
    appId: '1:902634485806:ios:92a979d9a9839e616e47bf',
    messagingSenderId: '902634485806',
    projectId: 'hostelmesss-9d0f2',
    storageBucket: 'hostelmesss-9d0f2.firebasestorage.app',
    iosBundleId: 'com.example.hostelmess1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ6KVjsC1Vlu_1HBA53qco0BR3wGsDDwo',
    appId: '1:902634485806:ios:92a979d9a9839e616e47bf',
    messagingSenderId: '902634485806',
    projectId: 'hostelmesss-9d0f2',
    storageBucket: 'hostelmesss-9d0f2.firebasestorage.app',
    iosBundleId: 'com.example.hostelmess1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZv2KyNB1tUS65ltj7eyOGQ_0w6QaOVKc',
    appId: '1:902634485806:web:8b74ff2124bda8986e47bf',
    messagingSenderId: '902634485806',
    projectId: 'hostelmesss-9d0f2',
    authDomain: 'hostelmesss-9d0f2.firebaseapp.com',
    storageBucket: 'hostelmesss-9d0f2.firebasestorage.app',
    measurementId: 'G-WFBQ0TXB08',
  );
}
